"use strict";
// automatically generated by the FlatBuffers compiler, do not modify
exports.__esModule = true;
exports.CustomOpT = exports.CustomOp = void 0;
var flatbuffers = require("flatbuffers");
var CustomOp = /** @class */ (function () {
    function CustomOp() {
        this.bb = null;
        this.bb_pos = 0;
    }
    CustomOp.prototype.__init = function (i, bb) {
        this.bb_pos = i;
        this.bb = bb;
        return this;
    };
    CustomOp.getRootAsCustomOp = function (bb, obj) {
        return (obj || new CustomOp()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
    };
    CustomOp.getSizePrefixedRootAsCustomOp = function (bb, obj) {
        bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
        return (obj || new CustomOp()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
    };
    CustomOp.prototype.dataType = function (optionalEncoding) {
        var offset = this.bb.__offset(this.bb_pos, 4);
        return offset ? this.bb.__string(this.bb_pos + offset, optionalEncoding) : null;
    };
    CustomOp.prototype.payload = function (optionalEncoding) {
        var offset = this.bb.__offset(this.bb_pos, 6);
        return offset ? this.bb.__string(this.bb_pos + offset, optionalEncoding) : null;
    };
    CustomOp.startCustomOp = function (builder) {
        builder.startObject(2);
    };
    CustomOp.addDataType = function (builder, dataTypeOffset) {
        builder.addFieldOffset(0, dataTypeOffset, 0);
    };
    CustomOp.addPayload = function (builder, payloadOffset) {
        builder.addFieldOffset(1, payloadOffset, 0);
    };
    CustomOp.endCustomOp = function (builder) {
        var offset = builder.endObject();
        builder.requiredField(offset, 4); // data_type
        builder.requiredField(offset, 6); // payload
        return offset;
    };
    CustomOp.createCustomOp = function (builder, dataTypeOffset, payloadOffset) {
        CustomOp.startCustomOp(builder);
        CustomOp.addDataType(builder, dataTypeOffset);
        CustomOp.addPayload(builder, payloadOffset);
        return CustomOp.endCustomOp(builder);
    };
    CustomOp.prototype.unpack = function () {
        return new CustomOpT(this.dataType(), this.payload());
    };
    CustomOp.prototype.unpackTo = function (_o) {
        _o.dataType = this.dataType();
        _o.payload = this.payload();
    };
    return CustomOp;
}());
exports.CustomOp = CustomOp;
var CustomOpT = /** @class */ (function () {
    function CustomOpT(dataType, payload) {
        if (dataType === void 0) { dataType = null; }
        if (payload === void 0) { payload = null; }
        this.dataType = dataType;
        this.payload = payload;
    }
    CustomOpT.prototype.pack = function (builder) {
        var dataType = (this.dataType !== null ? builder.createString(this.dataType) : 0);
        var payload = (this.payload !== null ? builder.createString(this.payload) : 0);
        return CustomOp.createCustomOp(builder, dataType, payload);
    };
    return CustomOpT;
}());
exports.CustomOpT = CustomOpT;
