"use strict";
// automatically generated by the FlatBuffers compiler, do not modify
exports.__esModule = true;
exports.DocUpdateT = exports.DocUpdate = void 0;
var flatbuffers = require("flatbuffers");
var DocUpdate = /** @class */ (function () {
    function DocUpdate() {
        this.bb = null;
        this.bb_pos = 0;
    }
    DocUpdate.prototype.__init = function (i, bb) {
        this.bb_pos = i;
        this.bb = bb;
        return this;
    };
    DocUpdate.getRootAsDocUpdate = function (bb, obj) {
        return (obj || new DocUpdate()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
    };
    DocUpdate.getSizePrefixedRootAsDocUpdate = function (bb, obj) {
        bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
        return (obj || new DocUpdate()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
    };
    DocUpdate.prototype.update = function (index) {
        var offset = this.bb.__offset(this.bb_pos, 4);
        return offset ? this.bb.readUint8(this.bb.__vector(this.bb_pos + offset) + index) : 0;
    };
    DocUpdate.prototype.updateLength = function () {
        var offset = this.bb.__offset(this.bb_pos, 4);
        return offset ? this.bb.__vector_len(this.bb_pos + offset) : 0;
    };
    DocUpdate.prototype.updateArray = function () {
        var offset = this.bb.__offset(this.bb_pos, 4);
        return offset ? new Uint8Array(this.bb.bytes().buffer, this.bb.bytes().byteOffset + this.bb.__vector(this.bb_pos + offset), this.bb.__vector_len(this.bb_pos + offset)) : null;
    };
    DocUpdate.startDocUpdate = function (builder) {
        builder.startObject(1);
    };
    DocUpdate.addUpdate = function (builder, updateOffset) {
        builder.addFieldOffset(0, updateOffset, 0);
    };
    DocUpdate.createUpdateVector = function (builder, data) {
        builder.startVector(1, data.length, 1);
        for (var i = data.length - 1; i >= 0; i--) {
            builder.addInt8(data[i]);
        }
        return builder.endVector();
    };
    DocUpdate.startUpdateVector = function (builder, numElems) {
        builder.startVector(1, numElems, 1);
    };
    DocUpdate.endDocUpdate = function (builder) {
        var offset = builder.endObject();
        return offset;
    };
    DocUpdate.createDocUpdate = function (builder, updateOffset) {
        DocUpdate.startDocUpdate(builder);
        DocUpdate.addUpdate(builder, updateOffset);
        return DocUpdate.endDocUpdate(builder);
    };
    DocUpdate.prototype.unpack = function () {
        return new DocUpdateT(this.bb.createScalarList(this.update.bind(this), this.updateLength()));
    };
    DocUpdate.prototype.unpackTo = function (_o) {
        _o.update = this.bb.createScalarList(this.update.bind(this), this.updateLength());
    };
    return DocUpdate;
}());
exports.DocUpdate = DocUpdate;
var DocUpdateT = /** @class */ (function () {
    function DocUpdateT(update) {
        if (update === void 0) { update = []; }
        this.update = update;
    }
    DocUpdateT.prototype.pack = function (builder) {
        var update = DocUpdate.createUpdateVector(builder, this.update);
        return DocUpdate.createDocUpdate(builder, update);
    };
    return DocUpdateT;
}());
exports.DocUpdateT = DocUpdateT;
