'use strict'
// automatically generated by the FlatBuffers compiler, do not modify
exports.__esModule = true
exports.unionListToMessageData = exports.unionToMessageData = exports.MessageData = void 0
var custom_op_1 = require('../networked-aframe/custom-op')
var presence_update_1 = require('../networked-aframe/presence-update')
var scene_update_1 = require('../networked-aframe/scene-update')
var MessageData;
(function (MessageData) {
  MessageData[MessageData['NONE'] = 0] = 'NONE'
  MessageData[MessageData['SceneUpdate'] = 1] = 'SceneUpdate'
  MessageData[MessageData['CustomOp'] = 2] = 'CustomOp'
  MessageData[MessageData['PresenceUpdate'] = 3] = 'PresenceUpdate'
})(MessageData = exports.MessageData || (exports.MessageData = {}))
function unionToMessageData (type, accessor) {
  switch (MessageData[type]) {
    case 'NONE': return null
    case 'SceneUpdate': return accessor(new scene_update_1.SceneUpdate())
    case 'CustomOp': return accessor(new custom_op_1.CustomOp())
    case 'PresenceUpdate': return accessor(new presence_update_1.PresenceUpdate())
    default: return null
  }
}
exports.unionToMessageData = unionToMessageData
function unionListToMessageData (type, accessor, index) {
  switch (MessageData[type]) {
    case 'NONE': return null
    case 'SceneUpdate': return accessor(index, new scene_update_1.SceneUpdate())
    case 'CustomOp': return accessor(index, new custom_op_1.CustomOp())
    case 'PresenceUpdate': return accessor(index, new presence_update_1.PresenceUpdate())
    default: return null
  }
}
exports.unionListToMessageData = unionListToMessageData
