"use strict";
// automatically generated by the FlatBuffers compiler, do not modify
exports.__esModule = true;
exports.unionListToOp = exports.unionToOp = exports.Op = void 0;
var delete_op_1 = require("../networked-aframe/delete-op");
var update_op_1 = require("../networked-aframe/update-op");
var Op;
(function (Op) {
    Op[Op["NONE"] = 0] = "NONE";
    Op[Op["UpdateOp"] = 1] = "UpdateOp";
    Op[Op["DeleteOp"] = 2] = "DeleteOp";
})(Op = exports.Op || (exports.Op = {}));
function unionToOp(type, accessor) {
    switch (Op[type]) {
        case 'NONE': return null;
        case 'UpdateOp': return accessor(new update_op_1.UpdateOp());
        case 'DeleteOp': return accessor(new delete_op_1.DeleteOp());
        default: return null;
    }
}
exports.unionToOp = unionToOp;
function unionListToOp(type, accessor, index) {
    switch (Op[type]) {
        case 'NONE': return null;
        case 'UpdateOp': return accessor(index, new update_op_1.UpdateOp());
        case 'DeleteOp': return accessor(index, new delete_op_1.DeleteOp());
        default: return null;
    }
}
exports.unionListToOp = unionListToOp;
