"use strict";
// automatically generated by the FlatBuffers compiler, do not modify
exports.__esModule = true;
exports.unionListToUpdateOpData = exports.unionToUpdateOpData = exports.UpdateOpData = void 0;
var full_update_op_1 = require("../networked-aframe/full-update-op");
var partial_update_op_1 = require("../networked-aframe/partial-update-op");
var UpdateOpData;
(function (UpdateOpData) {
    UpdateOpData[UpdateOpData["NONE"] = 0] = "NONE";
    UpdateOpData[UpdateOpData["FullUpdateOp"] = 1] = "FullUpdateOp";
    UpdateOpData[UpdateOpData["PartialUpdateOp"] = 2] = "PartialUpdateOp";
})(UpdateOpData = exports.UpdateOpData || (exports.UpdateOpData = {}));
function unionToUpdateOpData(type, accessor) {
    switch (UpdateOpData[type]) {
        case 'NONE': return null;
        case 'FullUpdateOp': return accessor(new full_update_op_1.FullUpdateOp());
        case 'PartialUpdateOp': return accessor(new partial_update_op_1.PartialUpdateOp());
        default: return null;
    }
}
exports.unionToUpdateOpData = unionToUpdateOpData;
function unionListToUpdateOpData(type, accessor, index) {
    switch (UpdateOpData[type]) {
        case 'NONE': return null;
        case 'FullUpdateOp': return accessor(index, new full_update_op_1.FullUpdateOp());
        case 'PartialUpdateOp': return accessor(index, new partial_update_op_1.PartialUpdateOp());
        default: return null;
    }
}
exports.unionListToUpdateOpData = unionListToUpdateOpData;
